In [1]:
import pandas as pd
dataset = pd.read_csv("CKD.csv")
dataset = pd.get_dummies(dataset, drop_first=True)
dataset = dataset.astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [2]:
print(dataset.head())
print(dataset.dtypes)

   age  bp  al  su  bgr  bu  sc  sod  pot  hrmo  ...  pc_normal  pcc_present  \
0    2  76   3   0  148  57   3  137    4    12  ...          0            0
1    3  76   2   0  148  22   0  137    4    10  ...          1            0
2    4  76   1   0   99  23   0  138    4    12  ...          1            0
3    5  76   1   0  148  16   0  138    3     8  ...          1            0
4    5  50   0   0  148  25   0  137    4    11  ...          1            0

   ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  \
0           0        0       0        0          1       1        0
1           0        0       0        0          1       0        0
2           0        0       0        0          1       0        0
3           0        0       0        0          1       0        1
4           0        0       0        0          1       0        0

   classification_yes
0                   1
1                   1
2                   1
3                   1
4                   1

[5 rows x 28 columns]
age                   int64
bp                    int64
al                    int64
su                    int64
bgr                   int64
bu                    int64
sc                    int64
sod                   int64
pot                   int64
hrmo                  int64
pcv                   int64
wc                    int64
rc                    int64
sg_b                  int64
sg_c                  int64
sg_d                  int64
sg_e                  int64
rbc_normal            int64
pc_normal             int64
pcc_present           int64
ba_present            int64
htn_yes               int64
dm_yes                int64
cad_yes               int64
appet_yes             int64
pe_yes                int64
ane_yes               int64
classification_yes    int64
dtype: object

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [9]:
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataset['classification_yes']

In [11]:
independent.shape

(399, 27)

In [13]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [57]:
#create Model
from sklearn.model_selection import GridSearchCV
#LogisticRegression
# from sklearn.linear_model import LogisticRegression
# param_grid = {'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'], 'penalty': ["l2"]}

#KNeighborsClassifier
#from sklearn.neighbors import KNeighborsClassifier
#param_grid = {'weights': ['uniform', 'distance'], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

#Random Forest
# from sklearn.ensemble import RandomForestClassifier
# param_grid = {'criterion': ['gini', 'entropy', 'log_loss'], 'max_features' : ['sqrt', 'log2'], 'class_weight' : ['None', 'balanced', 'balanced_subsample']}

#Decision Tree
# from sklearn.tree import DecisionTreeClassifier
# param_grid = {'criterion': ['gini', 'entropy', 'log_loss'], 'max_features' : ['sqrt', 'log2'], 'splitter' : ['best', 'random']}


#Naive_bayes - GaussianNB
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()

#Naive_bayes - MultinomialNB
# from sklearn.naive_bayes import MultinomialNB
# classifier = MultinomialNB()

#Naive_bayes - ComplementNB
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()

classifier.fit(xTrain, yTrain)
grid_predictions = classifier.predict(xTest)

# grid = GridSearchCV(LogisticRegression(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
#grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
# grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
# grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")


# grid.fit(xTrain, yTrain)

In [59]:
#print best parameter after tuning
re = grid.cv_results_
# print(re)

grid_predictions = grid.predict(xTest)

In [61]:
#print classification report
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, grid_predictions)

print(cm)

[[51  0]
 [ 6 76]]

In [63]:
from sklearn.metrics import classification_report
clfReport = classification_report(yTest, grid_predictions)
print(clfReport)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

In [41]:
from sklearn.metrics import f1_score
f1_macro = f1_score(yTest, grid_predictions, average="macro")
print('The f1_score of the best perameter {}:'.format(grid.best_params_), f1_macro)

The f1_score of the best perameter {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9532348804500703

In [55]:
tabel = pd.DataFrame.from_dict(re)
tabel

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.058650,0.020483,0.016717,0.006859,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.944707,0.981014,0.924528,0.962264,0.981031,0.958709,0.021784,6
1,0.030115,0.020731,0.021218,0.016879,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,1.000000,0.962573,0.981031,0.981031,0.984927,0.014032,1
2,0.006925,0.003776,0.003922,0.000934,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.981014,0.832761,0.981031,0.981217,0.944225,0.057448,10
3,0.003499,0.000539,0.003419,0.000678,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.981014,0.925524,0.962264,0.962573,0.966275,0.024678,5
4,0.003320,0.000190,0.003099,0.000500,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.926567,0.923510,0.887719,0.943093,0.961826,0.928543,0.024557,12
5,0.003016,0.000406,0.003083,0.000548,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981569,0.943699,0.981217,1.000000,1.000000,0.981297,0.020558,2
6,0.002741,0.000092,0.002763,0.000144,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981378,0.885265,0.907035,1.000000,0.961826,0.947101,0.043861,9
7,0.003046,0.000549,0.003275,0.000987,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.963284,0.962264,0.981217,0.981217,0.981217,0.973840,0.009041,3
8,0.004027,0.001301,0.002946,0.000326,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.944707,0.961755,0.944023,0.962264,0.943093,0.951169,0.008868,8
9,0.005293,0.001578,0.005112,0.001687,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.924528,0.925524,0.981031,0.943093,0.954835,0.030468,7
10,0.002918,0.000455,0.002930,0.000267,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.926567,0.962264,0.962573,0.906085,0.962264,0.943951,0.023467,11
11,0.002480,0.000235,0.002837,0.000495,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.922185,0.981217,0.962264,0.981217,0.969377,0.026442,4